var booksData = [
  {
    id: 0,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Improvement",
    year: "2018",
    type: "hardcover",
    image: "picture/Atomic Habits.png",
    reserved: false,
    description:
      "A powerful book on building good habits and breaking bad ones. James Clear provides practical strategies and insights backed by scientific research to help readers understand the psychology of habit formation and how to make positive changes in their lives.",
  },
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Fiction",
    year: "1960",
    type: "paperback",
    image: "picture/To Kill a Mockingbird.png",
    reserved: true,
    description:
      "Harper Lee's timeless classic explores themes of racial injustice and moral growth in the American South. Through the eyes of young Scout Finch, readers witness the trial of Tom Robinson, a black man falsely accused of raping a white woman, and the courage of her father, Atticus Finch, as he defends him.",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: "1949",
    type: "ebook",
    image: "picture/1984.jpg",
    reserved: false,
    description:
      "George Orwell's dystopian masterpiece paints a bleak picture of a totalitarian society ruled by Big Brother. Set in a future where surveillance is omnipresent and individuality is suppressed, the novel follows protagonist Winston Smith as he rebels against the oppressive regime and seeks freedom of thought",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    year: "1925",
    type: "hardcover",
    image: "picture/The Great Gatsby.png",
    reserved: false,
    description:
      "F. Scott Fitzgerald's classic novel captures the essence of the Jazz Age and the pursuit of the American Dream. Through the eyes of narrator Nick Carraway, readers are drawn into the world of Jay Gatsby, a mysterious millionaire, and his obsession with the elusive Daisy Buchanan.",
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Coming of Age",
    year: "1951",
    type: "paperback",
    image: "picture/The Catcher in the Rye.jpg",
    reserved: false,
    description:
      "J.D. Salinger's iconic coming-of-age novel follows the disillusioned teenager Holden Caulfield as he navigates the streets of New York City. Through Holden's cynical and introspective voice, the novel explores themes of alienation, identity, and the loss of innocence.",
  },
  {
    id: 5,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: "1997",
    type: "hardcover",
    image: "picture/Harry Potter and the Sorcerer's Stone.jpg",
    reserved: false,
    description:
      "The first installment in J.K. Rowling's beloved fantasy series introduces readers to the magical world of Hogwarts School of Witchcraft and Wizardry. Follow young Harry Potter as he discovers his true identity, makes friends, and confronts the dark wizard Voldemort.",
  },
  {
    id: 6,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: "1937",
    type: "ebook",
    image: "picture/The Hobbit.jpg",
    reserved: false,
    description:
      "A fantasy novel that follows the journey of Bilbo Baggins as he ventures to reclaim treasure guarded by a dragon.",
  },
  {
    id: 7,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    year: "2008",
    type: "paperback",
    image: "picture/The Hunger Games.jpg",
    reserved: true,
    description:
      "The first book in the Hunger Games trilogy, set in a dystopian future where children fight to the death in televised events.",
  },
  {
    id: 8,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Classic",
    year: "1813",
    type: "hardcover",
    image: "picture/Pride and Prejudice.jpg",
    reserved: false,
    description:
      "A classic novel that explores themes of love, class, and societal expectations in early 19th-century England.",
  },
  {
    id: 9,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Philosophical",
    year: "1988",
    type: "ebook",
    image: "picture/The Alchemist.jpg",
    reserved: false,
    description:
      "A philosophical novel that follows the journey of Santiago, a young shepherd, in pursuit of his personal legend.",
  },
  {
    id: 10,
    title: "Lord of the Flies",
    author: "William Golding",
    genre: "Allegory",
    year: "1954",
    type: "paperback",
    image: "picture/Lord of the Flies.jpg",
    reserved: false,
    description:
      "An allegorical novel that explores the descent into savagery when a group of boys is stranded on a deserted island.",
  },
  {
    id: 11,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    genre: "Fantasy",
    year: "1950",
    type: "hardcover",
    image: "picture/The Chronicles of Narnia.jpg",
    reserved: false,
    description:
      "A classic fantasy series that follows the adventures of children in the magical land of Narnia.",
  },
  {
    id: 12,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    genre: "Magical Realism",
    year: "1967",
    type: "paperback",
    image: "picture/One Hundred Years of Solitude.jpg",
    reserved: false,
    description:
      "A landmark novel in the magical realism genre, exploring the Buendía family's history in the fictional town of Macondo.",
  },
  {
    id: 13,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    year: "1932",
    type: "ebook",
    image: "picture/Brave New World.jpg",
    reserved: false,
    description:
      "A dystopian novel that explores a future society where technological advancements control every aspect of human life.",
  },
  {
    id: 14,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    year: "2011",
    type: "hardcover",
    image: "picture/Sapiens.jpg",
    reserved: false,
    description:
      "A thought-provoking exploration of human history, from the emergence of Homo sapiens to the present day.",
  },
  {
    id: 15,
    title: "The Shining",
    author: "Stephen King",
    genre: "Horror",
    year: "1977",
    type: "paperback",
    image: "picture/The Shining.jpg",
    reserved: false,
    description:
      "A classic horror novel that tells the story of the Torrance family's winter stay at the haunted Overlook Hotel.",
  },
  {
    id: 16,
    title: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-Apocalyptic",
    year: "2006",
    type: "ebook",
    image: "picture/The Road.jpg",
    reserved: false,
    description:
      "A post-apocalyptic novel following the journey of a father and son through a desolate and dangerous landscape.",
  },
  {
    id: 17,
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    genre: "Thriller",
    year: "2015",
    type: "paperback",
    image: "picture/The Girl on the Train.jpg",
    reserved: false,
    description:
      "A psychological thriller centered around a woman who becomes entangled in a missing person's investigation.",
  },
  {
    id: 18,
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    year: "2018",
    type: "hardcover",
    image: "picture/Educated.jpg",
    reserved: false,
    description:
      "A memoir recounting Tara Westover's journey from growing up in a strict and abusive household to earning a PhD from Cambridge University.",
  },
  {
    id: 19,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Psychological Thriller",
    year: "2019",
    type: "ebook",
    image: "picture/The Silent Patient.jpg",
    reserved: false,
    description:
      "A psychological thriller revolving around a woman who shoots her husband and then stops speaking, leading to a gripping mystery.",
  },
  {
    id: 20,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Mystery",
    year: "2018",
    type: "hardcover",
    image: "picture/Where the Crawdads Sing.jpg",
    reserved: false,
    description:
      "A mystery novel set in the marshes of North Carolina, exploring the life of Kya Clark, known as the 'Marsh Girl.'",
  },
];
